dataset: pubmed
mode: validation
seed: 0
features: 0
paper_leak: 0
paper_threshold: 0.951
train_ref: 1
feature_ref: 1
validation_ref: 1000
test_ref: 1000
topic_leak: 0
topic_threshold: 0
feature_leak: 0
feature_threshold: 1.159
graph_weight: 3.783
graph_delay: 1
train_to_topic_weight: 0.878
train_to_topic_delay: 1
validation_to_topic_weight: 0.027
validation_to_topic_delay: 1
test_to_topic_weight: 0.027
test_to_topic_delay: 1
paper_to_feature_weight: 0.795
feature_to_paper_weight: 2.665
paper_to_feature_delay: 1
simtime: 20
processes: 8
monitors: false
paper_to_feature_stdp: True
paper_to_feature_weighted: True
apos: [1.0, .5, .1, .01, .001]
aneg: [-0.0001]
stdp_timesteps: 5
dump_json: 1
