dataset: microseer  # Choices: ["cora", "citeseer", "pubmed", "microseer"]
mode: test  # Choices: ["validation", "test"]
nodes_path: !relpath ../../data/microseer/microseer.content
edges_path: !relpath ../../data/microseer/microseer.cites
seed: 120
train_topics_mult: 3  # multiply by num_topics to get number of papers
validation_topics_mult: 3  # multiply by num_topics to get number of papers
features: 0  # Choices: [0,1]
paper_leak: 0.0  # Choices: [1., 10., 100., 100000.]
paper_threshold: 1.0  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
train_ref: 1  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
feature_ref: 1  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
validation_ref: 1000  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
test_ref: 1000  # Same as validation_ref
topic_leak: 0.0  # Choices: [1., 10., 100., 100000.]
topic_threshold: 1.0  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
feature_leak: 0.0  # Choices: [1., 10., 100., 100000.]
feature_threshold: 0.25  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
graph_weight: 100.0  # Choices: [0.5, 1.0, 10.0, 100.0]
graph_delay: 1  # Choices: [1., 2., 5., 10., 20.]
train_to_topic_weight: 1.0  # Choices: [0.5, 1.0, 10.0, 100.0]
train_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
validation_to_topic_weight: 0.001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
validation_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
test_to_topic_weight: 0.001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
test_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
paper_to_feature_weight: 0.2  # Choices: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
feature_to_paper_weight: 0.2  # Choices: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
paper_to_feature_delay: 4  # Choices: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
simtime: 10  # Choices: [5., 10., 20., 30., 40., 50., 75., 100., 150., 200.]
monitors: False
paper_to_feature_stdp: False
paper_to_feature_weighted: False
apos: [1.0, .5, .1, .01, .001]
aneg: !np "[-0.0001] * 5"
stdp_timesteps: 5
dump_json: 1
backend: auto
processes: auto  # Adjust based on machine capabilities
gpu_processes: 8
